.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "GANDALF" 1 "" "Gandalf 0.2" "Gandalf Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
gandalf \- Control TCP forwarding for iDevices
.SH SYNOPSIS
.P
\fBgandalf\fR [\fIOPTION\fR]... 
.SH DESCRIPTION
.P
\fB gandalf\fR lets you ssh over USB to your jailbroken iDevices like iPhone, iPad, iTouch. You need to have the usbmuxd daemon running, on OS X this means you don't have to do anything but on Linux you need to install and run it.
.SH OPTIONS
.TP 4
\fB\-d\fR, \fB\-\-daemonize\fR
Whether\fB gandalf\fR should run as a daemon
.TP 4
\fB\-e\fR, \fB\-\-exit\fR
Gracefully exit current running relay
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-m\fR \fIVAL\fR, \fB\-\-mappings\fR=\fIVAL\fR
Simple file mapping udid to ports, expecting a file like 123gfdgefrgt234:2000
.TP 4
\fB\-r\fR, \fB\-\-reload\fR
Stop running threads and reload the mappings from the original mapping file path.
.TP 4
\fB\-s\fR, \fB\-\-status\fR
Pretty print json of currently tunneled devices
.TP 4
\fB\-t\fR \fIVAL\fR, \fB\-\-tries\fR=\fIVAL\fR (absent=3)
How many times to retry action
.TP 4
\fB\-v\fR, \fB\-\-verbose\fR
Output Debugging Info
.TP 4
\fB\-\-version\fR
Show version information.
.SH EXAMPLES
.P
1) See with realtime updates what devices are connected This will start up gandalf in listen mode, that is it will print out whenver a device connects or disconnects
.P
.nf
\fB gandalf\fR
.fi
.P
2) Start with a mapping file which is of the form <udid>:<port>, the # character starts comments.
.P
.nf
\fB gandalf\fR \-m mapping_file
.fi
.P
2.1) Daemonize \fB gandalf\fR with the \-d flag. *NOTE*: You might need to end up doing that under sudo as \fB gandalf\fR needs to make a pid file under /var/run. If daemonizing is failing, try running as root. After daemonzing, check the system log for debugging info
.P
3) See a pretty JSON representation of devices and their ports that are currently connected.
.P
.nf
\fB gandalf\fR \-s
.fi
.P
4) Reload \fB gandalf\fR with a new set of mappings
.P
.nf
\fB gandalf\fR \-r
.fi
.P
5) Cleanly exit \fB gandalf\fR, note this might requiresuper user permissions.
.P
.nf
\fB gandalf\fR \-e
.fi
.SH AUTHOR
.P
Edgar Aroutiounian