.\" Pipe this output to groff -man -Tutf8 | less
.\"
.TH "GANDALF" 1 "" "Gandalf 0.1" "Gandalf Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
gandalf \- Control TCP forwarding for sshing iDevices
.SH SYNOPSIS
.P
\fBgandalf\fR [\fIOPTION\fR]... 
.SH DESCRIPTION
.P
\fB gandalf\fR is a program for controlling the interface of ssh tcp iphone
.SH OPTIONS
.TP 4
\fB\-d\fR, \fB\-\-daemonize\fR
Whether\fB gandalf\fR should run as a daemon
.TP 4
\fB\-\-help\fR[=\fIFMT\fR] (default=pager)
Show this help in format \fIFMT\fR (pager, plain or groff).
.TP 4
\fB\-m\fR \fIVAL\fR, \fB\-\-mappings\fR=\fIVAL\fR
Simple file mapping udid to ports, expecting a file like 123gfdgefrgt234:2000
.TP 4
\fB\-t\fR \fIVAL\fR, \fB\-\-tries\fR=\fIVAL\fR (absent=3)
How many times to retry action
.TP 4
\fB\-v\fR, \fB\-\-verbose\fR
Output Debugging Info
.TP 4
\fB\-\-version\fR
Show version information.
.SH USAGE
.P
if\fB gandalf\fR is invoked with no arguments then it begins in listen mode, which means it will just show the DeviceIDs as assigned by usbmuxd and the device's udid.
.SH AUTHOR
.P
Edgar Aroutiounian