#+AUTHOR:   Edgar Aroutiounian
#+EMAIL:    edgar.factorial@gmail.com
#+LANGUAGE: en
#+STARTUP: indent
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+OPTIONS:  toc:nil num:0

This is a library and command line tool to control port forwarding to
jailbroken iOS devices.

Basically, it lets you do:

#+BEGIN_SRC shell
$ ssh root@localhost -p 2000
#+END_SRC

and you get a shell to an iDevice connected over a USB wire.

The command line tool is called ~gandalf~ and it requires that
~usbmuxd~ be running. If on OS X then you don't have to do anything,
if on Linux then you need to have the open source version of
[[https://github.com/libimobiledevice/usbmuxd][usbmuxd]]. I recommend compiling from source, versions on most package
managers are old.

* Installation
In this cloned repository, do: 

#+BEGIN_SRC shell
$ opam pin add usbmux . -y
#+END_SRC

This should install both the command line tool gandalf and the usbmux
OCaml library.

* gandalf usage.

The following are a series of usages of ~gandalf~, all short handle
arguments have long-forms as well and ~-v~ can be added at any time.

1) See with realtime updates what devices are connected 

   #+BEGIN_SRC shell
   $ gandalf
   #+END_SRC

   This will start up ~gandalf~ in listen mode, that is it will print
   out whenever a device connects or disconnects.

2) Start with a mapping file which is of the form ~<udid>:<port>~. The
   ~#~ character starts comments

   #+BEGIN_SRC shell
   $ gandalf -m mapping
   #+END_SRC

2.1) You can also daemonize ~gandalf~ with the ~-d~ flag. *NOTE*: You
might need to end up doing that under sudo as ~gandalf~ needs to
make a pid file under ~/var/run~.

3) To see a pretty JSON representation of devices and their ports that
   are currently connected, do:
   
   #+BEGIN_SRC shell
   $ gandalf -s
   #+END_SRC

4) To reload the ~gandalf~ with a new set of mappings, do:

   #+BEGIN_SRC shell
   $ gandalf -r
   #+END_SRC

   This will cancel all running threads and reload from the original
   mappings file, so make your changes there.


Check out the man page, accessible with:
#+BEGIN_SRC shell
$ gandalf --help
#+END_SRC

or 

#+BEGIN_SRC shell
$ man gandalf
#+END_SRC
